COLORTABLE = {
    "RedLight": [229, 117, 116],  # e57574	Geraldine       Pink
    "RedMedium": [202, 20, 21],  # ca1415	Venetian Red	Red
    "RedDark": [120, 0, 1],  # 780001	Sangria	        Dark Red
    "OrangeLight": [255, 178, 60],  # ffb23c	Supernova	    Light Orange
    "OrangeMedium": [255, 129, 18],  # ff8112	Pumpkin	        Orange
    "OrangeDark": [120, 61, 2],  # 783d02	Saddle Brown	Brown
    "YellowLight": [234, 225, 157],  # eae19d	Witch Haze	    Light Yellow
    "YellowMedium": [247, 216, 1],  # f7d801	School Bus Yellow	Yellow
    "YellowDark": [134, 114, 2],  # 867202	Olive	        Olive
    "GreenLight": [121, 224, 119],  # 79e077	Light Green	    Light Green
    "GreenMedium": [97, 255, 191],  # 61bf22	Kelly Green	    Green
    "GreenDark": [21, 108, 48],  # 156c30	Crusoe	        Dark Green
    "AquaLight": [125, 236, 227],  # 7dece3	Turquoise Blue	Cyan
    "AquaMedium": [0, 192, 155],  # 00c09b	Caribbean Green	Turquoise
    "AquaDark": [1, 79, 81],  # 014f51	Sherpa Blue	    Teal
    "BlueLight": [116, 163, 243],  # 74a3f3	Cornflower Blue	Light Blue
    "BlueMedium": [0, 79, 196],  # 004fce	Navy Blue	    Blue
    "BlueDark": [1, 42, 108],  # 012a6c	Sapphire	    Dark Blue
    "PurpleLight": [183, 128, 230],  # b780e6	Biloba Flower	Light Purple
    "PurpleMedium": [109, 0, 205],  # 6d00cd	Dark Violet     Purple
    "PurpleDark": [55, 0, 101],  # 370065	Purple	        Dark Purple
    "MagentaLight": [255, 153, 255],  # ff99ff	Violet	        Light Magenta
    "MagentaMedium": [255, 0, 255],  # ff00ff	Fuchsia	        Magenta
    "MagentaDark": [117, 0, 115],  # 750073	Purple	        Dark Magenta
    "WhiteLight": [249, 249, 249],  # f9f9f9	Snow	        White
    "WhiteMedium": [83, 83, 83],  # 535353	Matterhorn	    Dark Gray
    "WhiteMedium2": [234, 234, 234],  # aeaeae	Dark Gray	    Gray
    "Black": [24, 24, 24],  # 181818	Nero	        Black
}

COLORS_PRISM = {
    "COLOR_STANDARD_RED_LT": [229, 117, 116],
    "COLOR_STANDARD_RED_MD": [202, 20, 21],
    "COLOR_STANDARD_RED_DK": [120, 0, 1],
    "COLOR_STANDARD_ORANGE_LT": [255, 178, 60],
    "COLOR_STANDARD_ORANGE_MD": [255, 129, 18],
    "COLOR_STANDARD_ORANGE_DK": [120, 61, 2],
    #"COLOR_STANDARD_YELLOW_LT": [234, 225, 157],
    "COLOR_STANDARD_YELLOW_MD": [247, 216, 1],
    "COLOR_STANDARD_YELLOW_DK": [134, 114, 2],
    "COLOR_STANDARD_GREEN_LT": [121, 224, 119],
    "COLOR_STANDARD_GREEN_MD": [97, 191, 34],
    "COLOR_STANDARD_GREEN_DK": [21, 108, 48],
    "COLOR_STANDARD_AQUA_LT": [125, 236, 227],
    "COLOR_STANDARD_AQUA_MD": [0, 192, 155],
    "COLOR_STANDARD_AQUA_DK": [1, 79, 81],
    "COLOR_STANDARD_BLUE_LT": [116, 163, 243],
    "COLOR_STANDARD_BLUE_MD": [0, 79, 206],
    "COLOR_STANDARD_BLUE_DK": [1, 42, 108],
    "COLOR_STANDARD_PURPLE_LT": [183, 128, 230],
    "COLOR_STANDARD_PURPLE_MD": [109, 0, 205],
    "COLOR_STANDARD_PURPLE_DK": [55, 0, 101],
    "COLOR_STANDARD_MAGENTA_LT": [255, 153, 255],
    "COLOR_STANDARD_MAGENTA_MD": [255, 0, 255],
    "COLOR_STANDARD_MAGENTA_DK": [117, 0, 115],
    "COLOR_STANDARD_WHITE_LT": [249, 249, 249],
    "COLOR_STANDARD_WHITE_MD": [83, 83, 83],
    "COLOR_STANDARD_WHITE_MD2": [174, 174, 174],
    "COLOR_STANDARD_WHITE_DK": [24, 24, 24],
    "COLOR_SC_BRICK": [76, 0, 0],
    "COLOR_SC_LIGHT_BRICK": [158, 50, 50],
    "COLOR_SC_MEDIUM_BROWN": [85, 44, 0],
    "COLOR_SC_DARK_PERSIMMON": [188, 70, 0],
    "COLOR_SC_PERSIMMON": [236, 88, 0],
    "COLOR_SC_COCOA": [210, 105, 30],
    "COLOR_SC_LIGHT_BROWN": [170, 116, 57],
    "COLOR_SC_LIGHT_PERSIMMON": [255, 153, 92],
    "COLOR_SC_ORANGE": [248, 162, 2],
    "COLOR_SC_TAN": [221, 183, 106],
    "COLOR_SC_LIGHTEST_BROWN": [255, 214, 170],
    "COLOR_SC_BRIGHT_YELLOW": [254, 249, 0],
    "COLOR_SC_LIGHT_PASTEL_YELLOW": [255, 255, 188],
    "COLOR_SC_DARKEST_DRAB": [44, 65, 0],
    "COLOR_SC_DARK_DRAB": [73, 103, 9],
    "COLOR_SC_MEDIUM_DRAB": [108, 142, 35],
    "COLOR_SC_LIGHT_DRAB": [190, 220, 127],
    "COLOR_SC_DARK_GREEN": [0, 82, 0],
    "COLOR_SC_GREEN": [0, 170, 0],
    "COLOR_SC_LIGHT_GREEN": [66, 207, 66],
    "COLOR_SC_DARK_PASTEL_GREEN": [0, 152, 46],
    "COLOR_SC_LIGHT_PASTEL_GREEN": [83, 209, 121],
    "COLOR_SC_DARKEST_TEAL": [0, 117, 88],
    "COLOR_SC_DARK_TEAL": [2, 152, 114],
    "COLOR_SC_MEDIUM_TEAL": [97, 216, 186],
    "COLOR_SC_LIGHT_TEAL": [187, 245, 231],
    "COLOR_SC_DARK_CYAN": [0, 126, 162],
    "COLOR_SC_DARK_GREECE_BLUE": [13, 72, 124],
    "COLOR_SC_CYAN": [6, 200, 255],
    "COLOR_SC_LIGHT_CYAN": [85, 215, 252],
    "COLOR_SC_GREECE_BLUE": [50, 109, 162],
    "COLOR_SC_TRUE_BLUE": [16, 51, 166],
    "COLOR_SC_LIGHT_TRUE_BLUE": [43, 76, 186],
    "COLOR_SC_LIGHT_GREECE_BLUE": [168, 202, 233],
    "COLOR_SC_LIGHTEST_TRUE_BLUE": [112, 136, 213],
    "COLOR_SC_DARK_WISTERIA": [131, 73, 159],
    "COLOR_SC_WISTERIA": [166, 114, 191],
    "COLOR_SC_LIGHT_WISTERIA": [201, 160, 220],
    "COLOR_SC_DARK_PURPLE": [90, 0, 70],
    "COLOR_SC_MEDIUM_PURPLE": [146, 36, 122],
    "COLOR_SC_DARK_RED_VIOLET": [166, 0, 104],
    "COLOR_SC_RED_VIOLET": [199, 21, 113],
    "COLOR_SC_LIGHT_RED_VIOLET": [206, 58, 151],
    "COLOR_SC_LIGHTEST_RED_VIOLET": [219, 97, 174],
    "COLOR_SC_DARK_CRANBERRY": [165, 15, 22],
    "COLOR_SC_DARK_PINK": [254, 55, 108],
    "COLOR_SC_CRANBERRY": [206, 32, 41],
    "COLOR_SC_LIGHT_CRANBERRY": [224, 73, 81],
    "COLOR_SC_PINK": [255, 145, 175],
    "COLOR_SC_LIGHT_PINK": [255, 199, 214],
    "COLOR_SC_MEDIUM_GREY": [128, 128, 128],
    "COLOR_SC_LIGHT_GREY": [211, 211, 211],
    "COLOR_STANDARD_YELLOW_LT": [250, 236, 127],
}

CIV_OVERFLOW_COLORS = [
    "COLOR_SC_BRICK", "COLOR_STANDARD_MAGENTA_LT",
    "COLOR_SC_DARKEST_DRAB", "COLOR_SC_PINK",
    "COLOR_SC_DARK_GREECE_BLUE", "COLOR_SC_MEDIUM_TEAL",
    "COLOR_STANDARD_MAGENTA_MD", "COLOR_SC_DARK_PURPLE",
    "COLOR_SC_LIGHT_BRICK", "COLOR_SC_LIGHTEST_BROWN",
    "COLOR_SC_DARK_DRAB", "COLOR_SC_LIGHTEST_RED_VIOLET",
    "COLOR_SC_CYAN", "COLOR_SC_DARK_PURPLE",
    "COLOR_SC_DARK_RED_VIOLET", "COLOR_SC_LIGHT_GREECE_BLUE",
    "COLOR_STANDARD_RED_LT", "COLOR_SC_LIGHT_PINK",
    "COLOR_SC_MEDIUM_DRAB", "COLOR_STANDARD_RED_DK",
    "COLOR_STANDARD_BLUE_DK", "COLOR_SC_LIGHT_CYAN",
    "COLOR_STANDARD_MAGENTA_LT", "COLOR_SC_DARK_RED_VIOLET",
    "COLOR_SC_MEDIUM_BROWN", "COLOR_STANDARD_PURPLE_LT",
    "COLOR_STANDARD_GREEN_MD", "COLOR_SC_DARK_RED_VIOLET",
    "COLOR_SC_LIGHT_CYAN", "COLOR_SC_DARK_PERSIMMON",
    "COLOR_SC_RED_VIOLET", "COLOR_STANDARD_BLUE_DK",
    "COLOR_SC_DARK_PERSIMMON", "COLOR_STANDARD_BLUE_LT",
    "COLOR_SC_LIGHT_DRAB", "COLOR_SC_DARK_PERSIMMON",
    "COLOR_STANDARD_BLUE_MD", "COLOR_STANDARD_PURPLE_LT",
    "COLOR_SC_LIGHT_RED_VIOLET", "COLOR_STANDARD_AQUA_LT",
    "COLOR_STANDARD_ORANGE_DK", "COLOR_SC_LIGHT_DRAB",
    "COLOR_SC_DARK_GREEN", "COLOR_STANDARD_GREEN_LT",
    "COLOR_SC_GREECE_BLUE", "COLOR_STANDARD_BLUE_DK",
    "COLOR_SC_LIGHTEST_RED_VIOLET", "COLOR_SC_LIGHTEST_BROWN",
    "COLOR_SC_PERSIMMON", "COLOR_SC_DARK_PURPLE",
    "COLOR_SC_GREEN", "COLOR_SC_LIGHT_TEAL",
    "COLOR_SC_TRUE_BLUE", "COLOR_SC_DARK_TEAL",
    "COLOR_STANDARD_RED_DK", "COLOR_SC_LIGHT_WISTERIA",
    "COLOR_SC_COCOA", "COLOR_STANDARD_AQUA_LT",
    "COLOR_STANDARD_GREEN_LT", "COLOR_SC_CRANBERRY",
    "COLOR_SC_LIGHT_TRUE_BLUE", "COLOR_STANDARD_ORANGE_MD",
    "COLOR_SC_DARK_CRANBERRY", "COLOR_STANDARD_GREEN_LT",
    "COLOR_SC_LIGHT_BROWN", "COLOR_SC_DARK_GREEN",
    "COLOR_SC_LIGHT_GREEN", "COLOR_SC_DARK_RED_VIOLET",
    "COLOR_SC_LIGHT_GREECE_BLUE", "COLOR_SC_DARKEST_DRAB",
    "COLOR_STANDARD_RED_MD", "COLOR_SC_TAN",
    "COLOR_STANDARD_ORANGE_MD", "COLOR_STANDARD_YELLOW_LT",
    "COLOR_STANDARD_GREEN_DK", "COLOR_SC_LIGHT_PASTEL_GREEN",
    "COLOR_STANDARD_BLUE_LT", "COLOR_STANDARD_BLUE_DK",
    "COLOR_SC_DARK_PINK", "COLOR_SC_DARK_PURPLE",
    "COLOR_SC_LIGHT_PERSIMMON", "COLOR_SC_MEDIUM_PURPLE",
    "COLOR_SC_DARK_PASTEL_GREEN", "COLOR_STANDARD_AQUA_DK",
    "COLOR_SC_LIGHTEST_TRUE_BLUE", "COLOR_STANDARD_PURPLE_DK",
    "COLOR_SC_CRANBERRY", "COLOR_SC_LIGHT_DRAB",
    "COLOR_STANDARD_YELLOW_DK", "COLOR_STANDARD_MAGENTA_LT",
    "COLOR_SC_LIGHT_PASTEL_GREEN", "COLOR_STANDARD_PURPLE_DK",
    "COLOR_STANDARD_PURPLE_DK", "COLOR_SC_WISTERIA",
    "COLOR_SC_LIGHT_CRANBERRY", "COLOR_SC_LIGHT_CYAN",
    "COLOR_SC_ORANGE", "COLOR_SC_DARKEST_TEAL",
    "COLOR_SC_DARKEST_TEAL", "COLOR_STANDARD_BLUE_LT",
    "COLOR_STANDARD_PURPLE_MD", "COLOR_SC_LIGHTEST_BROWN",
    "COLOR_SC_PINK", "COLOR_STANDARD_BLUE_DK",
    "COLOR_STANDARD_ORANGE_LT", "COLOR_SC_DARK_WISTERIA",
    "COLOR_SC_DARK_TEAL", "COLOR_STANDARD_AQUA_LT",
    "COLOR_SC_DARK_WISTERIA", "COLOR_SC_LIGHT_PINK",
    "COLOR_SC_LIGHT_PINK", "COLOR_STANDARD_GREEN_DK",
    "COLOR_SC_TAN", "COLOR_STANDARD_BLUE_DK",
    "COLOR_STANDARD_AQUA_MD", "COLOR_STANDARD_MAGENTA_DK",
    "COLOR_STANDARD_PURPLE_LT", "COLOR_STANDARD_MAGENTA_DK",
    "COLOR_STANDARD_WHITE_MD", "COLOR_SC_TAN",
    "COLOR_SC_LIGHTEST_BROWN", "COLOR_SC_DARK_CYAN",
    "COLOR_SC_MEDIUM_TEAL", "COLOR_SC_DARK_GREEN",
    "COLOR_SC_WISTERIA", "COLOR_STANDARD_RED_DK",
    "COLOR_SC_MEDIUM_GREY", "COLOR_SC_LIGHT_TEAL",
    "COLOR_STANDARD_YELLOW_MD", "COLOR_STANDARD_WHITE_LT",
    "COLOR_SC_LIGHT_TEAL", "COLOR_SC_PERSIMMON",
    "COLOR_SC_LIGHT_WISTERIA", "COLOR_SC_DARK_GREECE_BLUE",
    "COLOR_STANDARD_WHITE_MD2", "COLOR_STANDARD_RED_DK",
    "COLOR_SC_BRIGHT_YELLOW", "COLOR_SC_DARK_PURPLE",
    "COLOR_STANDARD_AQUA_LT", "COLOR_SC_DARK_RED_VIOLET",
    "COLOR_STANDARD_MAGENTA_DK", "COLOR_STANDARD_AQUA_MD",
    "COLOR_SC_LIGHT_GREY", "COLOR_SC_DARK_GREEN",
    "COLOR_STANDARD_YELLOW_LT", "COLOR_STANDARD_WHITE_MD",
    "COLOR_STANDARD_AQUA_DK", "COLOR_SC_DARK_PINK",
    "COLOR_SC_DARK_PURPLE", "COLOR_SC_PINK",
    "COLOR_STANDARD_WHITE_LT", "COLOR_SC_DARK_PURPLE",
    "COLOR_SC_LIGHT_PASTEL_YELLOW", "COLOR_STANDARD_RED_MD",
    "COLOR_SC_DARK_CYAN", "COLOR_SC_LIGHT_DRAB",
    "COLOR_SC_MEDIUM_PURPLE", "COLOR_STANDARD_MAGENTA_LT",
]

CIV_LEADER_COLORS = {
    "ALEXANDER": ["COLOR_STANDARD_WHITE_MD2", "COLOR_SC_BRIGHT_YELLOW",
                  "COLOR_SC_DARK_GREECE_BLUE", "COLOR_STANDARD_YELLOW_LT",
                  "COLOR_STANDARD_ORANGE_DK", "COLOR_STANDARD_YELLOW_MD",
                  "COLOR_SC_DARK_CYAN", "COLOR_SC_LIGHT_CYAN"],
    "AMANITORE": ["COLOR_SC_TAN", "COLOR_STANDARD_ORANGE_DK",
                  "COLOR_SC_COCOA", "COLOR_SC_LIGHTEST_BROWN",
                  "COLOR_STANDARD_YELLOW_LT", "COLOR_SC_PERSIMMON",
                  "COLOR_SC_MEDIUM_PURPLE", "COLOR_SC_LIGHTEST_BROWN"],
    "BARBAROSSA": ["COLOR_SC_LIGHT_GREY", "COLOR_STANDARD_WHITE_DK",
                   "COLOR_SC_DARK_GREECE_BLUE", "COLOR_SC_LIGHT_GREY",
                   "COLOR_STANDARD_YELLOW_MD", "COLOR_STANDARD_WHITE_DK",
                   "COLOR_STANDARD_WHITE_MD", "COLOR_SC_LIGHT_GREY"],
    "CATHERINE_DE_MEDICI": ["COLOR_STANDARD_BLUE_MD", "COLOR_SC_BRIGHT_YELLOW",
                            "COLOR_STANDARD_WHITE_LT", "COLOR_STANDARD_YELLOW_DK",
                            "COLOR_SC_LIGHT_TRUE_BLUE", "COLOR_STANDARD_WHITE_LT",
                            "COLOR_SC_GREECE_BLUE", "COLOR_SC_BRIGHT_YELLOW"],
    "CHANDRAGUPTA": ["COLOR_STANDARD_AQUA_LT", "COLOR_STANDARD_PURPLE_DK",
                     "COLOR_SC_DARK_TEAL", "COLOR_SC_LIGHT_TEAL",
                     "COLOR_SC_MEDIUM_PURPLE", "COLOR_SC_MEDIUM_TEAL",
                     "COLOR_SC_DARK_DRAB", "COLOR_SC_LIGHT_PINK"],
    "CLEOPATRA": ["COLOR_STANDARD_AQUA_DK", "COLOR_SC_BRIGHT_YELLOW",
                  "COLOR_SC_DARKEST_TEAL", "COLOR_SC_BRIGHT_YELLOW",
                  "COLOR_SC_RED_VIOLET", "COLOR_SC_BRIGHT_YELLOW",
                  "COLOR_SC_BRIGHT_YELLOW", "COLOR_STANDARD_PURPLE_MD"],
    "JOHN_CURTIN": ["COLOR_STANDARD_GREEN_DK", "COLOR_STANDARD_YELLOW_MD",
                    "COLOR_STANDARD_YELLOW_MD", "COLOR_SC_DARK_GREEN",
                    "COLOR_STANDARD_BLUE_DK", "COLOR_STANDARD_WHITE_LT",
                    "COLOR_STANDARD_GREEN_LT", "COLOR_STANDARD_GREEN_DK"],
    "CYRUS": ["COLOR_SC_LIGHT_GREECE_BLUE", "COLOR_STANDARD_RED_DK",
              "COLOR_SC_LIGHT_PERSIMMON", "COLOR_STANDARD_BLUE_DK",
              "COLOR_STANDARD_AQUA_MD", "COLOR_STANDARD_RED_DK",
              "COLOR_SC_LIGHT_CYAN", "COLOR_SC_DARK_PURPLE"],
    "DIDO": ["COLOR_SC_MEDIUM_PURPLE", "COLOR_SC_LIGHT_WISTERIA",
             "COLOR_SC_DARK_WISTERIA", "COLOR_SC_LIGHT_GREY",
             "COLOR_SC_DARK_PURPLE", "COLOR_SC_LIGHT_WISTERIA",
             "COLOR_SC_LIGHT_GREY", "COLOR_STANDARD_PURPLE_MD"],
    "ELEANOR_ENGLAND": ["COLOR_SC_PINK", "COLOR_SC_LIGHT_PASTEL_YELLOW",
                        "COLOR_SC_DARK_PINK", "COLOR_SC_LIGHT_PASTEL_YELLOW",
                        "COLOR_STANDARD_RED_LT", "COLOR_SC_LIGHT_PASTEL_YELLOW",
                        "COLOR_SC_LIGHT_RED_VIOLET", "COLOR_SC_LIGHT_PASTEL_YELLOW"],
    "ELEANOR_FRANCE": ["COLOR_SC_LIGHT_WISTERIA", "COLOR_SC_LIGHT_PASTEL_YELLOW",
                       "COLOR_SC_WISTERIA", "COLOR_SC_LIGHT_PASTEL_YELLOW",
                       "COLOR_STANDARD_PURPLE_LT", "COLOR_SC_LIGHT_PASTEL_YELLOW",
                       "COLOR_SC_DARK_RED_VIOLET", "COLOR_SC_LIGHT_PASTEL_YELLOW"],
    "GANDHI": ["COLOR_SC_DARK_PURPLE", "COLOR_STANDARD_AQUA_LT",
               "COLOR_SC_LIGHT_RED_VIOLET", "COLOR_SC_LIGHT_PASTEL_YELLOW",
               "COLOR_SC_ORANGE", "COLOR_SC_TRUE_BLUE",
               "COLOR_SC_GREEN", "COLOR_STANDARD_ORANGE_LT"],
    "GENGHIS_KHAN": ["COLOR_SC_BRICK", "COLOR_SC_PERSIMMON",
                     "COLOR_STANDARD_ORANGE_MD", "COLOR_STANDARD_RED_DK",
                     "COLOR_SC_TAN", "COLOR_STANDARD_RED_DK",
                     "COLOR_SC_DARK_CRANBERRY", "COLOR_STANDARD_ORANGE_MD"],
    "GILGAMESH": ["COLOR_STANDARD_BLUE_DK", "COLOR_STANDARD_ORANGE_LT",
                  "COLOR_STANDARD_ORANGE_MD", "COLOR_STANDARD_BLUE_DK",
                  "COLOR_SC_LIGHT_PASTEL_YELLOW", "COLOR_STANDARD_BLUE_DK",
                  "COLOR_SC_TAN", "COLOR_STANDARD_BLUE_DK"],
    "GITARJA": ["COLOR_SC_CRANBERRY", "COLOR_STANDARD_AQUA_LT",
                "COLOR_SC_LIGHT_TEAL", "COLOR_SC_DARK_RED_VIOLET",
                "COLOR_STANDARD_PURPLE_LT", "COLOR_STANDARD_RED_DK",
                "COLOR_STANDARD_AQUA_LT", "COLOR_STANDARD_AQUA_LT"],
    "GORGO": ["COLOR_SC_LIGHT_BRICK", "COLOR_SC_LIGHT_GREECE_BLUE",
              "COLOR_SC_BRICK", "COLOR_SC_TAN",
              "COLOR_SC_PERSIMMON", "COLOR_STANDARD_WHITE_DK",
              "COLOR_STANDARD_YELLOW_DK", "COLOR_STANDARD_RED_DK"],
    "HARDRADA": ["COLOR_SC_TRUE_BLUE", "COLOR_STANDARD_RED_LT",
                 "COLOR_STANDARD_YELLOW_MD", "COLOR_SC_DARK_CRANBERRY",
                 "COLOR_STANDARD_BLUE_LT", "COLOR_SC_BRICK",
                 "COLOR_SC_LIGHT_CRANBERRY", "COLOR_STANDARD_BLUE_DK"],
    "HOJO": ["COLOR_STANDARD_WHITE_LT", "COLOR_STANDARD_RED_DK",
             "COLOR_SC_WISTERIA", "COLOR_STANDARD_BLUE_DK",
             "COLOR_STANDARD_RED_DK", "COLOR_STANDARD_YELLOW_MD",
             "COLOR_SC_TRUE_BLUE", "COLOR_STANDARD_WHITE_LT"],
    "JADWIGA": ["COLOR_STANDARD_RED_LT", "COLOR_SC_LIGHT_PASTEL_YELLOW",
                "COLOR_SC_LIGHTEST_RED_VIOLET", "COLOR_STANDARD_RED_DK",
                "COLOR_SC_RED_VIOLET", "COLOR_SC_LIGHT_PINK",
                "COLOR_SC_LIGHT_PINK", "COLOR_SC_CRANBERRY"],
    "JAYAVARMAN": ["COLOR_STANDARD_MAGENTA_DK", "COLOR_STANDARD_ORANGE_LT",
                   "COLOR_STANDARD_YELLOW_DK", "COLOR_STANDARD_BLUE_DK",
                   "COLOR_STANDARD_BLUE_DK", "COLOR_STANDARD_YELLOW_LT",
                   "COLOR_SC_LIGHT_PERSIMMON", "COLOR_STANDARD_BLUE_DK"],
    "KRISTINA": ["COLOR_STANDARD_BLUE_LT", "COLOR_SC_BRIGHT_YELLOW",
                 "COLOR_STANDARD_BLUE_MD", "COLOR_SC_BRIGHT_YELLOW",
                 "COLOR_SC_BRIGHT_YELLOW", "COLOR_SC_DARK_GREECE_BLUE",
                 "COLOR_SC_CYAN", "COLOR_STANDARD_BLUE_DK"],
    "KUPE": ["COLOR_SC_LIGHT_CRANBERRY", "COLOR_SC_LIGHT_GREECE_BLUE",
             "COLOR_STANDARD_RED_MD", "COLOR_SC_LIGHT_GREY",
             "COLOR_STANDARD_WHITE_MD", "COLOR_STANDARD_WHITE_LT",
             "COLOR_SC_MEDIUM_DRAB", "COLOR_SC_LIGHT_CYAN"],
    "LAURIER": ["COLOR_STANDARD_WHITE_LT", "COLOR_STANDARD_RED_MD",
                "COLOR_SC_LIGHT_PINK", "COLOR_STANDARD_RED_MD",
                "COLOR_SC_TRUE_BLUE", "COLOR_STANDARD_WHITE_LT",
                "COLOR_SC_DARK_PASTEL_GREEN", "COLOR_SC_PINK"],
    "LAUTARO": ["COLOR_SC_DARK_GREECE_BLUE", "COLOR_SC_LIGHT_GREECE_BLUE",
                "COLOR_STANDARD_ORANGE_DK", "COLOR_SC_LIGHTEST_BROWN",
                "COLOR_SC_DARKEST_DRAB", "COLOR_SC_LIGHT_TEAL",
                "COLOR_SC_LIGHTEST_BROWN", "COLOR_STANDARD_BLUE_DK"],
    "MATTHIAS_CORVINUS": ["COLOR_SC_DARK_GREEN", "COLOR_SC_LIGHT_CRANBERRY",
                          "COLOR_SC_CRANBERRY", "COLOR_STANDARD_WHITE_LT",
                          "COLOR_STANDARD_BLUE_MD", "COLOR_STANDARD_WHITE_DK",
                          "COLOR_SC_LIGHT_GREEN", "COLOR_STANDARD_RED_MD"],
    "MONTEZUMA": ["COLOR_SC_MEDIUM_TEAL", "COLOR_STANDARD_RED_MD",
                  "COLOR_STANDARD_RED_DK", "COLOR_SC_MEDIUM_TEAL",
                  "COLOR_SC_LIGHT_TEAL", "COLOR_SC_DARKEST_DRAB",
                  "COLOR_SC_LIGHT_DRAB", "COLOR_SC_DARK_CRANBERRY"],
    "MANSA_MUSA": ["COLOR_SC_DARK_PERSIMMON", "COLOR_SC_LIGHT_PASTEL_YELLOW",
                   "COLOR_STANDARD_RED_DK", "COLOR_STANDARD_YELLOW_LT",
                   "COLOR_SC_MEDIUM_BROWN", "COLOR_SC_LIGHT_PERSIMMON",
                   "COLOR_SC_LIGHT_BROWN", "COLOR_STANDARD_RED_DK"],
    "MVEMBA": ["COLOR_SC_BRIGHT_YELLOW", "COLOR_STANDARD_RED_MD",
               "COLOR_SC_CRANBERRY", "COLOR_SC_LIGHT_GREY",
               "COLOR_SC_DARK_DRAB", "COLOR_SC_LIGHT_GREY",
               "COLOR_STANDARD_GREEN_MD", "COLOR_STANDARD_BLUE_DK"],
    "PACHACUTI": ["COLOR_SC_PERSIMMON", "COLOR_STANDARD_YELLOW_MD",
                  "COLOR_STANDARD_ORANGE_DK", "COLOR_STANDARD_YELLOW_MD",
                  "COLOR_SC_DARK_GREEN", "COLOR_SC_PERSIMMON",
                  "COLOR_STANDARD_PURPLE_MD", "COLOR_STANDARD_WHITE_LT"],
    "PEDRO": ["COLOR_SC_GREEN", "COLOR_SC_BRIGHT_YELLOW",
              "COLOR_SC_TRUE_BLUE", "COLOR_SC_BRIGHT_YELLOW",
              "COLOR_STANDARD_GREEN_MD", "COLOR_STANDARD_BLUE_DK",
              "COLOR_SC_LIGHT_GREEN", "COLOR_SC_BRIGHT_YELLOW"],
    "PERICLES": ["COLOR_SC_GREECE_BLUE", "COLOR_STANDARD_WHITE_LT",
                 "COLOR_SC_DARK_TEAL", "COLOR_STANDARD_WHITE_LT",
                 "COLOR_SC_LIGHT_GREECE_BLUE", "COLOR_SC_DARK_GREECE_BLUE",
                 "COLOR_SC_PERSIMMON", "COLOR_STANDARD_WHITE_DK"],
    "PETER_GREAT": ["COLOR_STANDARD_YELLOW_MD", "COLOR_STANDARD_WHITE_DK",
                    "COLOR_SC_DARK_DRAB", "COLOR_STANDARD_YELLOW_LT",
                    "COLOR_STANDARD_WHITE_LT", "COLOR_STANDARD_BLUE_MD",
                    "COLOR_SC_LIGHTEST_TRUE_BLUE", "COLOR_STANDARD_WHITE_LT"],
    "PHILIP_II": ["COLOR_STANDARD_RED_MD", "COLOR_SC_BRIGHT_YELLOW",
                  "COLOR_SC_DARK_WISTERIA", "COLOR_SC_BRIGHT_YELLOW",
                  "COLOR_STANDARD_YELLOW_MD", "COLOR_SC_MEDIUM_PURPLE",
                  "COLOR_SC_BRICK", "COLOR_STANDARD_RED_LT"],
    "POUNDMAKER": ["COLOR_SC_LIGHTEST_BROWN", "COLOR_STANDARD_ORANGE_DK",
                   "COLOR_STANDARD_BLUE_DK", "COLOR_STANDARD_GREEN_MD",
                   "COLOR_STANDARD_AQUA_DK", "COLOR_SC_LIGHT_CYAN",
                   "COLOR_SC_LIGHT_PASTEL_GREEN", "COLOR_SC_DARK_GREEN"],
    "QIN": ["COLOR_SC_MEDIUM_DRAB", "COLOR_STANDARD_WHITE_LT",
            "COLOR_SC_BRIGHT_YELLOW", "COLOR_SC_DARK_GREECE_BLUE",
            "COLOR_STANDARD_AQUA_DK", "COLOR_SC_LIGHT_PASTEL_GREEN",
            "COLOR_SC_DARK_CRANBERRY", "COLOR_STANDARD_PURPLE_LT"],
    "ROBERT_THE_BRUCE": ["COLOR_SC_LIGHTEST_TRUE_BLUE", "COLOR_STANDARD_WHITE_LT",
                         "COLOR_STANDARD_BLUE_LT", "COLOR_STANDARD_WHITE_LT",
                         "COLOR_SC_BRIGHT_YELLOW", "COLOR_STANDARD_RED_MD",
                         "COLOR_SC_LIGHT_GREECE_BLUE", "COLOR_SC_DARK_GREECE_BLUE"],
    "SALADIN": ["COLOR_STANDARD_YELLOW_MD", "COLOR_STANDARD_GREEN_DK",
                "COLOR_SC_DARK_PASTEL_GREEN", "COLOR_SC_LIGHT_PASTEL_YELLOW",
                "COLOR_SC_MEDIUM_GREY", "COLOR_STANDARD_YELLOW_LT",
                "COLOR_STANDARD_GREEN_DK", "COLOR_STANDARD_GREEN_LT"],
    "SEONDEOK": ["COLOR_SC_DARK_CRANBERRY", "COLOR_STANDARD_BLUE_LT",
                 "COLOR_STANDARD_MAGENTA_LT", "COLOR_STANDARD_MAGENTA_DK",
                 "COLOR_STANDARD_PURPLE_MD", "COLOR_SC_PINK",
                 "COLOR_SC_LIGHTEST_RED_VIOLET", "COLOR_STANDARD_BLUE_DK"],
    "SHAKA": ["COLOR_SC_DARKEST_DRAB", "COLOR_SC_LIGHT_PASTEL_YELLOW",
              "COLOR_STANDARD_ORANGE_DK", "COLOR_SC_LIGHTEST_BROWN",
              "COLOR_SC_LIGHT_PASTEL_GREEN", "COLOR_STANDARD_RED_MD",
              "COLOR_SC_LIGHT_DRAB", "COLOR_SC_DARK_GREEN"],
    "SULEIMAN": ["COLOR_SC_LIGHT_PASTEL_YELLOW", "COLOR_SC_DARK_GREEN",
                 "COLOR_SC_DARK_GREEN", "COLOR_STANDARD_YELLOW_LT",
                 "COLOR_STANDARD_YELLOW_LT", "COLOR_STANDARD_RED_MD",
                 "COLOR_STANDARD_RED_MD", "COLOR_STANDARD_YELLOW_LT"],
    "TAMAR": ["COLOR_STANDARD_WHITE_LT", "COLOR_STANDARD_ORANGE_MD",
              "COLOR_SC_DARK_RED_VIOLET", "COLOR_SC_LIGHT_PINK",
              "COLOR_SC_GREECE_BLUE", "COLOR_STANDARD_YELLOW_MD",
              "COLOR_SC_LIGHT_GREY", "COLOR_STANDARD_RED_MD"],
    "T_ROOSEVELT": ["COLOR_SC_LIGHT_TRUE_BLUE", "COLOR_STANDARD_WHITE_LT",
                    "COLOR_STANDARD_BLUE_DK", "COLOR_SC_LIGHT_GREY",
                    "COLOR_SC_DARK_CYAN", "COLOR_SC_LIGHT_GREY",
                    "COLOR_STANDARD_WHITE_MD2", "COLOR_STANDARD_BLUE_DK"],
    "TOMYRIS": ["COLOR_STANDARD_YELLOW_LT", "COLOR_STANDARD_RED_MD",
                "COLOR_SC_MEDIUM_BROWN", "COLOR_SC_LIGHT_GREECE_BLUE",
                "COLOR_SC_CYAN", "COLOR_SC_BRIGHT_YELLOW",
                "COLOR_SC_COCOA", "COLOR_STANDARD_BLUE_DK"],
    "TRAJAN": ["COLOR_STANDARD_PURPLE_DK", "COLOR_SC_BRIGHT_YELLOW",
               "COLOR_SC_DARK_PURPLE", "COLOR_SC_BRIGHT_YELLOW",
               "COLOR_SC_DARK_WISTERIA", "COLOR_SC_BRIGHT_YELLOW",
               "COLOR_SC_DARK_RED_VIOLET", "COLOR_SC_BRIGHT_YELLOW"],
    "VICTORIA": ["COLOR_STANDARD_RED_DK", "COLOR_STANDARD_WHITE_LT",
                 "COLOR_SC_PINK", "COLOR_SC_LIGHT_PASTEL_YELLOW",
                 "COLOR_SC_LIGHT_PINK", "COLOR_STANDARD_RED_MD",
                 "COLOR_SC_LIGHT_WISTERIA", "COLOR_STANDARD_RED_DK"],
    "WILHELMINA": ["COLOR_SC_ORANGE", "COLOR_STANDARD_WHITE_LT",
                   "COLOR_SC_LIGHT_TRUE_BLUE", "COLOR_STANDARD_ORANGE_LT",
                   "COLOR_STANDARD_ORANGE_MD", "COLOR_STANDARD_WHITE_LT",
                   "COLOR_STANDARD_ORANGE_LT", "COLOR_STANDARD_BLUE_DK"],
    "SIMON_BOLIVAR": ["COLOR_STANDARD_BLUE_DK", "COLOR_SC_BRIGHT_YELLOW",
                      "COLOR_SC_CYAN", "COLOR_SC_BRIGHT_YELLOW",
                      "COLOR_SC_BRIGHT_YELLOW", "COLOR_STANDARD_BLUE_DK",
                      "COLOR_STANDARD_RED_MD", "COLOR_SC_LIGHT_CYAN"],
    "LADY_SIX_SKY": ["COLOR_SC_LIGHT_CYAN", "COLOR_STANDARD_AQUA_DK",
                     "COLOR_STANDARD_AQUA_DK", "COLOR_STANDARD_BLUE_LT",
                     "COLOR_SC_DARK_CYAN", "COLOR_SC_TAN",
                     "COLOR_SC_DARK_DRAB", "COLOR_STANDARD_YELLOW_LT"],
    "MENELIK": ["COLOR_SC_DARK_CYAN", "COLOR_SC_BRIGHT_YELLOW",
                "COLOR_SC_DARK_PASTEL_GREEN", "COLOR_SC_BRIGHT_YELLOW",
                "COLOR_SC_DARK_GREEN", "COLOR_SC_LIGHT_CRANBERRY",
                "COLOR_SC_CYAN", "COLOR_SC_BRIGHT_YELLOW"],
    "CATHERINE_DE_MEDICI_ALT": ["COLOR_SC_LIGHT_PERSIMMON", "COLOR_STANDARD_WHITE_LT",
                                "COLOR_STANDARD_BLUE_MD", "COLOR_SC_BRIGHT_YELLOW",
                                "COLOR_STANDARD_WHITE_LT", "COLOR_STANDARD_YELLOW_DK",
                                "COLOR_SC_GREECE_BLUE", "COLOR_SC_BRIGHT_YELLOW"],
    "T_ROOSEVELT_ROUGHRIDER": ["COLOR_STANDARD_ORANGE_LT", "COLOR_STANDARD_BLUE_DK",
                               "COLOR_SC_LIGHT_TRUE_BLUE", "COLOR_STANDARD_WHITE_LT",
                               "COLOR_SC_DARK_CYAN", "COLOR_SC_LIGHT_GREY",
                               "COLOR_STANDARD_WHITE_MD2", "COLOR_STANDARD_BLUE_DK"],
    "AMBIORIX": ["COLOR_SC_DARKEST_TEAL", "COLOR_SC_LIGHT_TEAL",
                 "COLOR_SC_DARK_CYAN", "COLOR_STANDARD_YELLOW_MD",
                 "COLOR_STANDARD_GREEN_DK", "COLOR_SC_LIGHT_GREECE_BLUE",
                 "COLOR_STANDARD_YELLOW_LT", "COLOR_STANDARD_GREEN_DK"],
    "BASIL": ["COLOR_SC_DARK_WISTERIA", "COLOR_STANDARD_YELLOW_MD",
              "COLOR_STANDARD_WHITE_MD", "COLOR_SC_BRIGHT_YELLOW",
              "COLOR_STANDARD_BLUE_LT", "COLOR_STANDARD_MAGENTA_DK",
              "COLOR_STANDARD_RED_MD", "COLOR_SC_BRIGHT_YELLOW"],
    "HAMMURABI": ["COLOR_SC_DARK_GREECE_BLUE", "COLOR_STANDARD_YELLOW_MD",
                  "COLOR_SC_LIGHT_BROWN", "COLOR_STANDARD_YELLOW_LT",
                  "COLOR_STANDARD_BLUE_LT", "COLOR_STANDARD_BLUE_DK",
                  "COLOR_STANDARD_AQUA_DK", "COLOR_STANDARD_AQUA_LT"],
}

# CIV_COLORS = {
# "AMERICA":           [{"territory": COLORTABLE["BlueDark"],     "city": COLORTABLE["WhiteLight",
# {"territory": COLORTABLE["RedMedium"],    "city": COLORTABLE["WhiteLight",
# {"territory": COLORTABLE["WhiteLight"],   "city": COLORTABLE["BlueDark",
# {"territory": COLORTABLE["BlueDark"],     "city": COLORTABLE["RedMedium"]}],
# "ARABIA":            [{"territory": COLORTABLE["YellowMedium"], "city": COLORTABLE["GreenDark",
# {"territory": COLORTABLE["GreenDark"],    "city": COLORTABLE["GreenMedium",
# {"territory": COLORTABLE["GreenMedium"],  "city": COLORTABLE["Black",
# {"territory": COLORTABLE["YellowDark"],   "city": COLORTABLE["GreenMedium"]}],
# "AUSTRALIA":         [{"territory": COLORTABLE["GreenDark"],    "city": COLORTABLE["BlueDark",
# {"territory": COLORTABLE["WhiteLight"],   "city": COLORTABLE["BlueDark",
# {"territory": COLORTABLE["BlueDark"],     "city": COLORTABLE["BlueDark",
# {"territory": COLORTABLE["WhiteLight"],   "city": COLORTABLE["BlueDark"]}],
# "AZTEC":             [{"territory": COLORTABLE["AquaLight"],    "city": COLORTABLE["RedDark",
# {"territory": COLORTABLE["RedDark"],      "city": COLORTABLE["AquaLight",
# {"territory": COLORTABLE["OrangeMedium"], "city": COLORTABLE["AquaDark",
# {"territory": COLORTABLE["AquaDark"],     "city": COLORTABLE["OrangeMedium"]}],
# "BABYLON":           [{"territory": COLORTABLE["BlueLight"],    "city": COLORTABLE["BlueDark",
# {"territory": COLORTABLE["YellowLight"],  "city": COLORTABLE["BlueDark",
# {"territory": COLORTABLE["BlueDark"],     "city": COLORTABLE["WhiteLight",
# {"territory": COLORTABLE["BlueDark"],     "city": COLORTABLE["YellowMedium"]}],
# "BRAZIL":            [{"territory": COLORTABLE["GreenLight"],   "city": COLORTABLE["YellowMedium",
# {"territory": COLORTABLE["GreenLight"],   "city": COLORTABLE["BlueDark",
# {"territory": COLORTABLE["YellowMedium"], "city": COLORTABLE["GreenDark",
# {"territory": COLORTABLE["BlueDark"],     "city": COLORTABLE["GreenLight"]}],
# "BYZANTIUM":         [{"territory": COLORTABLE["PurpleDark"],   "city": COLORTABLE["YellowLight",
# {"territory": COLORTABLE["RedDark"],      "city": COLORTABLE["YellowMedium",
# {"territory": COLORTABLE["YellowMedium"], "city": COLORTABLE["RedDark",
# {"territory": COLORTABLE["BlueDark"],     "city": COLORTABLE["PurpleMedium"]}],
# "CANADA":            [{"territory": COLORTABLE["WhiteLight"],   "city": COLORTABLE["RedMedium",
# {"territory": COLORTABLE["RedMedium"],    "city": COLORTABLE["WhiteLight",
# {"territory": COLORTABLE["RedDark"],      "city": COLORTABLE["RedLight",
# {"territory": COLORTABLE["RedLight"],     "city": COLORTABLE["RedDark"]}],
# "CHINA":             [{"territory": COLORTABLE["GreenDark"],    "city": COLORTABLE["WhiteLight",
# {"territory": COLORTABLE["RedMedium"],    "city": COLORTABLE["YellowMedium",
# {"territory": COLORTABLE["YellowMedium"], "city": COLORTABLE["RedMedium",
# {"territory": COLORTABLE["YellowMedium"], "city": COLORTABLE["BlueDark"]}],
# "CREE":              [{"territory": COLORTABLE["BlueDark"],     "city": COLORTABLE["GreenLight",
# {"territory": COLORTABLE["GreenLight"],   "city": COLORTABLE["BlueDark",
# {"territory": COLORTABLE["BlueLight"],    "city": COLORTABLE["YellowMedium",
# {"territory": COLORTABLE["GreenLight"],   "city": COLORTABLE["YellowMedium"]}],
# "EGYPT":             [{"territory": COLORTABLE["AquaDark"],     "city": COLORTABLE["YellowLight",
# {"territory": COLORTABLE["YellowLight"],  "city": COLORTABLE["PurpleMedium",
# {"territory": COLORTABLE["YellowLight"],  "city": COLORTABLE["AquaDark",
# {"territory": COLORTABLE["PurpleMedium"], "city": COLORTABLE["YellowLight"]}],
# "ENGLAND":           [{"territory": COLORTABLE["RedMedium"],    "city": COLORTABLE["WhiteLight",
# {"territory": COLORTABLE["WhiteLight"],   "city": COLORTABLE["RedMedium",
# {"territory": COLORTABLE["BlueDark"],     "city": COLORTABLE["RedMedium",
# {"territory": COLORTABLE["RedMedium"],    "city": COLORTABLE["BlueDark"]}],
# "ETHIOPIA":          [{"territory": COLORTABLE["YellowMedium"], "city": COLORTABLE["GreenDark",
# {"territory": COLORTABLE["GreenDark"],    "city": COLORTABLE["YellowMedium",
# {"territory": COLORTABLE["RedMedium"],    "city": COLORTABLE["YellowMedium",
# {"territory": COLORTABLE["GreenDark"],    "city": COLORTABLE["RedMedium"]}],
# "FRANCE":            [{"territory": COLORTABLE["BlueMedium"],   "city": COLORTABLE["YellowLight",
# {"territory": COLORTABLE["WhiteLight"],   "city": COLORTABLE["YellowDark",
# {"territory": COLORTABLE["WhiteLight"],   "city": COLORTABLE["BlueMedium",
# {"territory": COLORTABLE["BlueDark"],     "city": COLORTABLE["RedMedium"]}],
# "GAUL":              [{"territory": COLORTABLE["GreenDark"],    "city": COLORTABLE["AquaLight",
# {"territory": COLORTABLE["YellowLight"],  "city": COLORTABLE["GreenDark",
# {"territory": COLORTABLE["OrangeDark"],   "city": COLORTABLE["OrangeMedium",
# {"territory": COLORTABLE["OrangeMedium"], "city": COLORTABLE["YellowLight"]}],
# "GEORGIA":           [{"territory": COLORTABLE["WhiteLight"],   "city": COLORTABLE["OrangeLight",
# {"territory": COLORTABLE["WhiteLight"],   "city": COLORTABLE["RedMedium",
# {"territory": COLORTABLE["RedDark"],      "city": COLORTABLE["WhiteLight",
# {"territory": COLORTABLE["YellowMedium"], "city": COLORTABLE["Black"]}],
# "GERMANY":           [{"territory": COLORTABLE["WhiteMedium2"], "city": COLORTABLE["Black",
# {"territory": COLORTABLE["YellowMedium"], "city": COLORTABLE["Black",
# {"territory": COLORTABLE["RedMedium"],    "city": COLORTABLE["WhiteLight",
# {"territory": COLORTABLE["YellowMedium"], "city": COLORTABLE["RedMedium"]}],
# "GREECE":            [{"territory": COLORTABLE["BlueLight"],    "city": COLORTABLE["WhiteLight",
# {"territory": COLORTABLE["WhiteLight"],   "city": COLORTABLE["BlueLight",
# {"territory": COLORTABLE["BlueLight"],    "city": COLORTABLE["BlueDark",
# {"territory": COLORTABLE["BlueDark"],     "city": COLORTABLE["BlueLight"]}],
# "GRAN_COLOMBIA":     [{"territory": COLORTABLE["BlueDark"],     "city": COLORTABLE["YellowMedium",
# {"territory": COLORTABLE["BlueDark"],     "city": COLORTABLE["RedMedium",
# {"territory": COLORTABLE["RedMedium"],    "city": COLORTABLE["BlueDark",
# {"territory": COLORTABLE["YellowLight"],  "city": COLORTABLE["RedDark"]}],
# "HUNGARY":           [{"territory": COLORTABLE["GreenDark"],    "city": COLORTABLE["OrangeMedium",
# {"territory": COLORTABLE["WhiteLight"],   "city": COLORTABLE["GreenDark",
# {"territory": COLORTABLE["GreenDark"],    "city": COLORTABLE["RedMedium",
# {"territory": COLORTABLE["GreenDark"],    "city": COLORTABLE["WhiteLight"]}],
# "INCA":              [{"territory": COLORTABLE["OrangeDark"],   "city": COLORTABLE["YellowMedium",
# {"territory": COLORTABLE["OrangeLight"],  "city": COLORTABLE["AquaDark",
# {"territory": COLORTABLE["YellowMedium"], "city": COLORTABLE["OrangeDark",
# {"territory": COLORTABLE["AquaDark"],     "city": COLORTABLE["OrangeLight"]}],
# "INDIA":             [{"territory": COLORTABLE["PurpleDark"],   "city": COLORTABLE["AquaMedium",
# {"territory": COLORTABLE["AquaMedium"],   "city": COLORTABLE["PurpleDark",
# {"territory": COLORTABLE["GreenDark"],    "city": COLORTABLE["OrangeLight",
# {"territory": COLORTABLE["OrangeLight"],  "city": COLORTABLE["GreenDark"]}],
# "INDONESIA":         [{"territory": COLORTABLE["RedDark"],      "city": COLORTABLE["AquaMedium",
# {"territory": COLORTABLE["AquaMedium"],   "city": COLORTABLE["RedDark",
# {"territory": COLORTABLE["RedMedium"],    "city": COLORTABLE["WhiteLight",
# {"territory": COLORTABLE["BlueDark"],     "city": COLORTABLE["AquaMedium"]}],
# "JAPAN":             [{"territory": COLORTABLE["WhiteLight"],   "city": COLORTABLE["RedDark",
# {"territory": COLORTABLE["RedDark"],      "city": COLORTABLE["WhiteLight",
# {"territory": COLORTABLE["BlueMedium"],   "city": COLORTABLE["WhiteLight",
# {"territory": COLORTABLE["WhiteLight"],   "city": COLORTABLE["BlueMedium"]}],
# "KHMER":             [{"territory": COLORTABLE["MagentaDark"],  "city": COLORTABLE["OrangeMedium",
# {"territory": COLORTABLE["BlueDark"],     "city": COLORTABLE["YellowLight",
# {"territory": COLORTABLE["OrangeDark"],   "city": COLORTABLE["OrangeMedium",
# {"territory": COLORTABLE["OrangeMedium"], "city": COLORTABLE["MagentaDark"]}],
# "KONGO":             [{"territory": COLORTABLE["YellowMedium"], "city": COLORTABLE["RedMedium",
# {"territory": COLORTABLE["RedMedium"],    "city": COLORTABLE["YellowMedium",
# {"territory": COLORTABLE["GreenLight"],   "city": COLORTABLE["OrangeDark",
# {"territory": COLORTABLE["OrangeDark"],   "city": COLORTABLE["GreenLight"]}],
# "KOREA":             [{"territory": COLORTABLE["RedMedium"],    "city": COLORTABLE["BlueLight",
# {"territory": COLORTABLE["BlueLight"],    "city": COLORTABLE["RedMedium",
# {"territory": COLORTABLE["OrangeMedium"], "city": COLORTABLE["WhiteLight",
# {"territory": COLORTABLE["WhiteLight"],   "city": COLORTABLE["OrangeMedium"]}],
# "MACEDON":           [{"territory": COLORTABLE["WhiteMedium2"], "city": COLORTABLE["YellowMedium",
# {"territory": COLORTABLE["BlueDark"],     "city": COLORTABLE["YellowMedium",
# {"territory": COLORTABLE["RedMedium"],    "city": COLORTABLE["YellowMedium",
# {"territory": COLORTABLE["YellowMedium"], "city": COLORTABLE["BlueDark"]}],
# "MALI":              [{"territory": COLORTABLE["RedDark"],      "city": COLORTABLE["YellowLight",
# {"territory": COLORTABLE["YellowLight"],  "city": COLORTABLE["RedDark",
# {"territory": COLORTABLE["YellowDark"],   "city": COLORTABLE["WhiteLight",
# {"territory": COLORTABLE["YellowDark"],   "city": COLORTABLE["GreenLight"]}],
# "MAORI":             [{"territory": COLORTABLE["RedMedium"],    "city": COLORTABLE["AquaLight",
# {"territory": COLORTABLE["AquaLight"],    "city": COLORTABLE["RedMedium",
# {"territory": COLORTABLE["AquaMedium"],   "city": COLORTABLE["AquaLight",
# {"territory": COLORTABLE["OrangeDark"],   "city": COLORTABLE["YellowLight"]}],
# "MAPUCHE":           [{"territory": COLORTABLE["BlueMedium"],   "city": COLORTABLE["AquaLight",
# {"territory": COLORTABLE["YellowMedium"], "city": COLORTABLE["RedDark",
# {"territory": COLORTABLE["YellowLight"],  "city": COLORTABLE["OrangeDark",
# {"territory": COLORTABLE["BlueLight"],    "city": COLORTABLE["BlueDark"]}],
# "MAYA":              [{"territory": COLORTABLE["BlueLight"],    "city": COLORTABLE["AquaDark",
# {"territory": COLORTABLE["AquaDark"],     "city": COLORTABLE["BlueLight",
# {"territory": COLORTABLE["GreenDark"],    "city": COLORTABLE["YellowLight",
# {"territory": COLORTABLE["OrangeLight"],  "city": COLORTABLE["AquaDark"]}],
# "MONGOLIA":          [{"territory": COLORTABLE["RedDark"],      "city": COLORTABLE["OrangeMedium",
# {"territory": COLORTABLE["OrangeMedium"], "city": COLORTABLE["RedDark",
# {"territory": COLORTABLE["YellowLight"],  "city": COLORTABLE["RedDark",
# {"territory": COLORTABLE["RedDark"],      "city": COLORTABLE["YellowMedium"]}],
# "NETHERLANDS":       [{"territory": COLORTABLE["OrangeMedium"], "city": COLORTABLE["BlueMedium",
# {"territory": COLORTABLE["OrangeMedium"], "city": COLORTABLE["WhiteLight",
# {"territory": COLORTABLE["OrangeMedium"], "city": COLORTABLE["OrangeLight",
# {"territory": COLORTABLE["OrangeMedium"], "city": COLORTABLE["RedDark"]}],
# "NORWAY":            [{"territory": COLORTABLE["BlueDark"],     "city": COLORTABLE["RedMedium",
# {"territory": COLORTABLE["RedMedium"],    "city": COLORTABLE["BlueDark",
# {"territory": COLORTABLE["RedMedium"],    "city": COLORTABLE["YellowMedium",
# {"territory": COLORTABLE["YellowMedium"], "city": COLORTABLE["RedMedium"]}],
# "NUBIA":             [{"territory": COLORTABLE["YellowLight"],  "city": COLORTABLE["OrangeDark",
# {"territory": COLORTABLE["OrangeDark"],   "city": COLORTABLE["YellowLight",
# {"territory": COLORTABLE["WhiteLight"],   "city": COLORTABLE["OrangeDark",
# {"territory": COLORTABLE["OrangeDark"],   "city": COLORTABLE["WhiteLight"]}],
# "OTTOMAN":           [{"territory": COLORTABLE["WhiteLight"],   "city": COLORTABLE["GreenDark",
# {"territory": COLORTABLE["RedMedium"],    "city": COLORTABLE["WhiteLight",
# {"territory": COLORTABLE["GreenDark"],    "city": COLORTABLE["WhiteLight",
# {"territory": COLORTABLE["GreenDark"],    "city": COLORTABLE["RedLight"]}],
# "PERSIA":            [{"territory": COLORTABLE["PurpleLight"],  "city": COLORTABLE["RedDark",
# {"territory": COLORTABLE["RedDark"],      "city": COLORTABLE["PurpleLight",
# {"territory": COLORTABLE["RedMedium"],    "city": COLORTABLE["YellowMedium",
# {"territory": COLORTABLE["AquaMedium"],   "city": COLORTABLE["RedDark"]}],
# "PHOENICIA":         [{"territory": COLORTABLE["PurpleMedium"], "city": COLORTABLE["BlueLight",
# {"territory": COLORTABLE["PurpleMedium"], "city": COLORTABLE["WhiteLight",
# {"territory": COLORTABLE["PurpleDark"],   "city": COLORTABLE["OrangeLight",
# {"territory": COLORTABLE["WhiteLight"],   "city": COLORTABLE["PurpleDark"]}],
# "POLAND":            [{"territory": COLORTABLE["RedDark"],      "city": COLORTABLE["RedLight",
# {"territory": COLORTABLE["WhiteLight"],   "city": COLORTABLE["RedLight",
# {"territory": COLORTABLE["BlueDark"],     "city": COLORTABLE["WhiteLight",
# {"territory": COLORTABLE["WhiteLight"],   "city": COLORTABLE["BlueDark"]}],
# "ROME":              [{"territory": COLORTABLE["PurpleMedium"], "city": COLORTABLE["YellowMedium",
# {"territory": COLORTABLE["RedDark"],      "city": COLORTABLE["YellowMedium",
# {"territory": COLORTABLE["YellowMedium"], "city": COLORTABLE["PurpleDark",
# {"territory": COLORTABLE["PurpleMedium"], "city": COLORTABLE["WhiteLight"]}],
# "RUSSIA":            [{"territory": COLORTABLE["YellowMedium"], "city": COLORTABLE["Black",
# {"territory": COLORTABLE["WhiteLight"],   "city": COLORTABLE["BlueMedium",
# {"territory": COLORTABLE["BlueMedium"],   "city": COLORTABLE["WhiteLight",
# {"territory": COLORTABLE["BlueDark"],     "city": COLORTABLE["RedLight"]}],
# "SCOTLAND":          [{"territory": COLORTABLE["WhiteLight"],   "city": COLORTABLE["BlueMedium",
# {"territory": COLORTABLE["BlueMedium"],   "city": COLORTABLE["WhiteLight",
# {"territory": COLORTABLE["YellowMedium"], "city": COLORTABLE["RedMedium",
# {"territory": COLORTABLE["YellowMedium"], "city": COLORTABLE["BlueMedium"]}],
# "SCYTHIA":           [{"territory": COLORTABLE["OrangeLight"],  "city": COLORTABLE["RedDark",
# {"territory": COLORTABLE["OrangeDark"],   "city": COLORTABLE["WhiteLight",
# {"territory": COLORTABLE["RedDark"],      "city": COLORTABLE["YellowLight",
# {"territory": COLORTABLE["OrangeDark"],   "city": COLORTABLE["YellowLight"]}],
# "SPAIN":             [{"territory": COLORTABLE["RedMedium"],    "city": COLORTABLE["YellowMedium",
# {"territory": COLORTABLE["YellowMedium"], "city": COLORTABLE["RedMedium",
# {"territory": COLORTABLE["RedMedium"],    "city": COLORTABLE["BlueDark",
# {"territory": COLORTABLE["BlueDark"],     "city": COLORTABLE["RedMedium"]}],
# "SUMERIA":           [{"territory": COLORTABLE["BlueDark"],     "city": COLORTABLE["OrangeMedium",
# {"territory": COLORTABLE["BlueDark"],     "city": COLORTABLE["AquaLight",
# {"territory": COLORTABLE["OrangeMedium"], "city": COLORTABLE["BlueDark",
# {"territory": COLORTABLE["BlueDark"],     "city": COLORTABLE["PurpleMedium"]}],
# "SWEDEN":            [{"territory": COLORTABLE["BlueLight"],    "city": COLORTABLE["YellowMedium",
# {"territory": COLORTABLE["YellowMedium"], "city": COLORTABLE["BlueDark",
# {"territory": COLORTABLE["BlueMedium"],   "city": COLORTABLE["WhiteLight",
# {"territory": COLORTABLE["WhiteLight"],   "city": COLORTABLE["BlueDark"]}],
# "ZULU":              [{"territory": COLORTABLE["OrangeDark"],   "city": COLORTABLE["WhiteLight",
# {"territory": COLORTABLE["GreenDark"],    "city": COLORTABLE["YellowLight",
# {"territory": COLORTABLE["WhiteLight"],   "city": COLORTABLE["OrangeDark",
# {"territory": COLORTABLE["GreenMedium"],  "city": COLORTABLE["Black"]}],
# }

# window.CIV_COLORS = {
# 	America:           {city: [255, 255, 255], territory: [ 31,  51, 120,
# 	Arabia:            {city: [146, 221,   9], territory: [ 43,  87,  45,
# 	Assyria:           {city: [255, 168,  12], territory: [255, 243, 173,
# 	Austria:           {city: [255, 255, 255], territory: [234,   0,   0,
# 	Babylon:           {city: [200, 248, 255], territory: [ 43,  81,  97,
# 	Brazil:            {city: [ 41,  83,  44], territory: [149, 221,  10,
# 	Byzantium:         {city: [ 60,   0, 108], territory: [113, 161, 232,
# 	Carthage:          {city: [ 80,   0, 136], territory: [204, 204, 204,
# 	China:             {city: [255, 255, 255], territory: [  0, 148,  82,
# 	Denmark:           {city: [239, 231, 179], territory: [108,  42,  20,
# 	Egypt:             {city: [ 82,   0, 208], territory: [255, 251,   3,
# 	England:           {city: [255, 255, 255], territory: [108,   2,   0,
# 	Ethiopia:          {city: [255,  45,  45], territory: [  1,  39,  14,
# 	France:            {city: [235, 235, 138], territory: [ 65, 141, 253,
# 	Germany:           {city: [ 36,  43,  32], territory: [179, 177, 184,
# 	Greece:            {city: [ 65, 141, 253], territory: [255, 255, 255,
# 	India:             {city: [255, 153,  49], territory: [ 18, 135,   6,
# 	Indonesia:         {city: [158,  46,  28], territory: [110, 210, 217,
# 	Japan:             {city: [184,   0,   0], territory: [255, 255, 255,
# 	Korea:             {city: [255,   0,   0], territory: [ 26,  32,  96,
# 	Mongolia:          {city: [255, 120,   0], territory: [ 81,   0,   8,
# 	Morocco:           {city: [ 39, 178,  79], territory: [144,   2,   0,
# 	Persia:            {city: [245, 230,  55], territory: [176,   7,   3,
# 	Poland:            {city: [ 56,   0,   0], territory: [244,   5,   0,
# 	Polynesia:         {city: [255, 255,  74], territory: [217,  88,   0,
# 	Portugal:          {city: [  3,  20, 124], territory: [255, 255, 255,
# 	Rome:              {city: [239, 198,   0], territory: [ 70,   0, 118,
# 	Russia:            {city: [  0,   0,   0], territory: [238, 238, 238,
# 	Siam:              {city: [176,   7,   3], territory: [245, 230,  55,
# 	Songhai:           {city: [ 90,   0,   9], territory: [213, 145,  19,
# 	Spain:             {city: [244, 168, 168], territory: [ 83,  26,  26,
# 	Sweden:            {city: [248, 246,   2], territory: [  7,   7, 165,
# 	Venice:            {city: [255, 254, 215], territory: [102,  33, 161,
# 	'The Aztecs':      {city: [136, 238, 212], territory: [161,  57,  34,
# 	'The Celts':       {city: [147, 169, 255], territory: [ 21,  91,  62,
# 	'The Huns':        {city: [ 69,   0,   3], territory: [179, 177, 163,
# 	'The Inca':        {city: [  6, 159, 119], territory: [255, 184,  33,
# 	'The Iroquois':    {city: [251, 201, 129], territory: [ 65,  86,  86,
# 	'The Maya':        {city: [ 23,  62,  65], territory: [197, 140,  98,
# 	'The Netherlands': {city: [255, 255, 255], territory: [255, 143,   0,
# 	'The Ottomans':    {city: [ 18,  82,  30], territory: [247, 248, 199,
# 	'The Shoshone':    {city: [ 24, 239, 206], territory: [ 73,  58,  45,
# 	'The Zulus':       {city: [106,  49,  24], territory: [255, 231, 213]}
# }
